services:

  postgis:
    image: postgis/postgis:17-3.5
    container_name: land_postgis
    restart: unless-stopped

    environment:
      POSTGRES_DB: landdb
      POSTGRES_USER: satyam
      POSTGRES_PASSWORD: abc@123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: